version: '3'

services:
  docker-registry:
    image: registry
    restart: unless-stopped
    environment:
    - REGISTRY_AUTH=htpasswd
    - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/volume
    - REGISTRY_HTTP_TLS_CERTIFICATE=/etc/server.crt
    - REGISTRY_HTTP_TLS_KEY=/etc/server.key
    - REGISTRY_STORAGE_DELETE_ENABLED=True
    ports:
    - 6000:5000
    volumes:
    - ./auth:/auth
    - ./volume:/volume
    - ./server.key:/etc/server.key
    - ./server.crt:/etc/server.crt
