version: '3'

services:
  docker-registry:
    image: registry:latest
    restart: unless-stopped
    environment:
    - REGISTRY_AUTH=htpasswd
    - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/volume
    - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/fullchain.pem
    - REGISTRY_HTTP_TLS_KEY=/certs/privkey.pem
    - REGISTRY_STORAGE_DELETE_ENABLED=True
    ports:
    - 5000:5000
    volumes:
    - ./auth:/auth
    - ./volume:/volume
    - ./certs/fullchain.pem:/certs/fullchain.pem
    - ./certs/privkey.pem:/certs/privkey.pem
